### ISSUE TITLE
Struggling with Ollama

### ISSUE THREAD

**Issue by bamit99** [MervinPraison/PraisonAI#10]
Hi, I am running Ollama on my machine and it's working properly. I have multiple tools including CrewAI, PrivateGPT and others that can utilize it. Although, somehow I am not even able to initiate PraisonAI to use Ollama. It keeps giving me error about the OpenAI key. I have updated the .env file as below but the error keeps coming "
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)"

How to fix this?! Also, where should the env file be stored.

OPENAI_API_BASE=http://localhost:11434/v1
OPENAI_MODEL_NAME=Majinbu

**Comment by bamit99** [comment]
My mistake. My API was on PC IP rather than loopback. I changed it and it works now.

**Comment by zsb87** [comment]
@bamit99  I have tried both loopback and IP address "http://127.0.0.1:11434/v1" but always got error. How did you solve it?
`File "C:\Users\zhanshib\AppData\Roaming\Python\Python312\site-packages\openai\_base_client.py", line 952, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.`
