### ISSUE TITLE
How to use claude ?

### ISSUE THREAD

**Issue by ameerfayiz** [MervinPraison/PraisonAI#11]
i tried setting 

OPENAI_API_BASE = https://api.anthropic.com/v1/messages
or 
OPENAI_API_BASE = https://api.anthropic.com/v1
and 
OPENAI_MODEL_NAME = claude-3-opus-20240229

along with proper OPENAI_API_KEY.

but it gives error :

  File "C:\Users\Ameer\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'type': 'error', 'error': {'type': 'not_found_error', 'message': 'Not Found'}}

what am i doing wrong ? i can use grok and openAi without error

**Comment by MervinPraison** [comment]
You could follow this doc to use Claude https://docs.praison.ai/models/anthropic/
