### ISSUE TITLE
ubuntu 22 log show a lot of warning - its normal

### ISSUE THREAD

**Issue by johnfelipe** [MervinPraison/PraisonAI#137]
https://gist.github.com/johnfelipe/53a5f9f29a68a73ee3976e23fe602880

can u tell me if is good?

**Comment by MervinPraison** [comment]
Seems like a warning specific to your computer. Please try any other computer, It should work. 

or alternatively try this. It's recommendation from ChatGPT

```
echo 'export PATH=$PATH:/home/felipe/.local/bin' >> ~/.bashrc
source ~/.bashrc
```

**Comment by johnfelipe** [comment]
solved with your suggestion
