### ISSUE TITLE
CrewAI Telemetry - posthog

### ISSUE THREAD

**Issue by manjaroblack** [MervinPraison/PraisonAI#57]
Telemetry is “disabled” for CrewAI in PraisonAI, however when the CrewAI_Tools are loaded the telemetry is sent to posthog. My adblocker is blocking the communication to posthog, therefore an error is generated, see below. A similar message is generated for each tool and the retries cause a significant delay in the PraisonAI process.

```
_common.py-_common:105 - INFO: Backing off send_request(...) for 0.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002AAF9D125D0>: Failed to resolve 'us-api.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
```

**Comment by yiouyou** [comment]
Me too, the same problem here~

**Comment by MervinPraison** [comment]
@manjaroblack @yiouyou This issue has been fixed. Can you please update and confirm if it's all good?

`pip install -U "praisonai[ui]"`
