### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by charlesbiggs07** [MervinPraison/PraisonAI#7]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-cloud-auth 0.1.4 requires pydantic<2.0, but you have pydantic 2.6.4 which is incompatible.

When I change to pydantic<2.0, the dependency issue continues to trickle down.

I'm having this same issue when I tried to install and run CrewAI last weekend.  (Already raised an issue there but have yet to hear back.)

Thanks.

**Comment by MervinPraison** [comment]
@charlesbiggs07 is this still an issue?

**Comment by MervinPraison** [comment]
@charlesbiggs07 Hoping this issue has been fixed, so closing it. If you still face issue please raise an issue ticket. Thanks
