### ISSUE TITLE
Praisonai code not working on linux

### ISSUE THREAD

**Issue by DRomatzki** [MervinPraison/PraisonAI#86]
Hi 
I am trying to run praisonai on linuxmint. I installed a conda environment and ran the code.
1) firstly the  database is created by root, or so it seemed, since it was read only and I had to change it.
2) I only use Ollama and tried as in the video. It works till you try to chat. It prints the words and then bombs out back. to the logging page. LiteLLM says nothing special or gives a hint. it did so when I fiddeld around before, but not in the latests instances. On restart it remembers the models, etc so the database is working now.
3) The consol/terminal shows no errors to guide me
4) I tried to create a docker image but could not get it to work, neither on praisonai nor on praisonai code. After a lot of changes pot the dockerfile it ran but the webpage never opened and the program gets stuck. BTW it requests the installation of "duckduckgo_search". So it is missing in the requirements.txt

**Comment by MervinPraison** [comment]
@DRomatzki 
Thanks for pointing these all out. 

Did you try the default username and password. 

"admin" for both.

**Comment by masterchop** [comment]
admin/admin didnt work for me so i added the following variables to .env file:
`export CHAINLIT_USERNAME=admin`
`export CHAINLIT_PASSWORD=admin`

**Comment by MervinPraison** [comment]
@DRomatzki I hope you tried using admin and admin as the default user name and password. 
That should fix the issue. Please create another ticket if you find any issue again. Thanks for reporting.
