### ISSUE TITLE
Only picking up python files and its content

### ISSUE THREAD

**Issue by gittmaan** [MervinPraison/PraisonAI#91]
I am able to run this locally with Ollama and Deepseek-coder-v2
But somehow its only picking up python and .py file content but shows all file tree
is there a way we can use javascript/typescript files and its content?

**Comment by MervinPraison** [comment]
@gittmaan Thanks for reporting. Please check now and let me know if you still face issues. 
Please upgrade to the latest version

**Comment by gittmaan** [comment]
I have ``` Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /opt/homebrew/Caskroom/miniforge/base/envs/praison/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=2.14.1->google-cloud-aiplatform<2.0.0,>=1.26.1->embedchain<0.2.0,>=0.1.113->crewai>=0.32.0->praisonai[code]) (0.6.0) ``` still its not picking `js` / `ts` code I am running `pip install "praisonai[code]"` and `praisonai code`

**Comment by MervinPraison** [comment]
@gittmaan `pip install -U "praisonai[code]"` to upgrade . Please try after that and let me know. Thanks

**Comment by MervinPraison** [comment]
@gittmaan Should be fixed in this version: https://github.com/MervinPraison/PraisonAI/releases/tag/v0.0.52

**Comment by gittmaan** [comment]
@MervinPraison Awesome! I needed to uninstall and install it again and it seems working now thanks 🙏🏼
